alter table public.profiles enable row level security;
alter table public.teams enable row level security;
alter table public.team_members enable row level security;
alter table public.projects enable row level security;
alter table public.simulation_runs enable row level security;
alter table public.billing_events enable row level security;
alter table public.usage enable row level security;
create policy "Users can view own profile" on public.profiles for select using (auth.uid() = id);
create policy "Users can update own profile" on public.profiles for update using (auth.uid() = id);
create policy "Team members can view teams" on public.teams for select using (id in (select team_id from public.team_members where user_id = auth.uid()));
create policy "Users can create teams" on public.teams for insert with check (owner_id = auth.uid());
create policy "Members can view team members" on public.team_members for select using (team_id in (select team_id from public.team_members where user_id = auth.uid()));
create policy "Team members can view projects" on public.projects for select using (team_id in (select team_id from public.team_members where user_id = auth.uid()));
create policy "Team members can create projects" on public.projects for insert with check (team_id in (select team_id from public.team_members where user_id = auth.uid()));
create policy "Team members can view runs" on public.simulation_runs for select using (team_id in (select team_id from public.team_members where user_id = auth.uid()));
create policy "Team members can create runs" on public.simulation_runs for insert with check (team_id in (select team_id from public.team_members where user_id = auth.uid()));
create policy "Team members can view usage" on public.usage for select using (team_id in (select team_id from public.team_members where user_id = auth.uid()));
create policy "Team admins can view billing" on public.billing_events for select using (team_id in (select team_id from public.team_members where user_id = auth.uid() and role in ('owner', 'admin')));
create or replace function public.handle_new_user() returns trigger as $$ begin insert into public.profiles (id, email, full_name, avatar_url) values (new.id, new.email, new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'avatar_url'); return new; end; $$ language plpgsql security definer;
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute function public.handle_new_user();
create index if not exists idx_simulation_runs_team on public.simulation_runs(team_id);
create index if not exists idx_simulation_runs_created on public.simulation_runs(created_at desc);
create index if not exists idx_projects_team on public.projects(team_id);
create index if not exists idx_team_members_user on public.team_members(user_id);
create index if not exists idx_usage_team_month on public.usage(team_id, month);
