import type { MetadataRoute } from "next";

// SEOMETA-02: Disallow all authenticated app pages to prevent SEO pollution
const APP_PATHS = [
  "/api/",
  "/dashboard",
  "/settings",
  "/simulate",
  "/apm",
  "/dora",
  "/compliance",
  "/reports",
  "/incidents",
  "/traffic-light",
  "/postmortems",
  "/runbooks",
  "/calendar",
  "/timeline",
  "/teams",
  "/projects",
  "/remediation",
  "/suggestions",
  "/whatif",
  "/fmea",
  "/benchmark",
  "/sla-budget",
  "/sla",
  "/topology",
  "/dependencies",
  "/heatmap",
  "/people-risk",
  "/score-detail",
  "/topology-map",
  "/governance",
  "/fisc",
  "/audit-report",
  "/compliance-report",
  "/evidence",
  "/shadow-it",
  "/bus-factor",
  "/vuln-priority",
  "/external-impact",
  "/iac",
  "/gameday",
  "/ai-reliability",
  "/advisor",
  "/drift",
  "/env-compare",
  "/canary",
  "/supply-chain",
  "/traces",
  "/logs",
  "/optimize",
  "/onboarding",
  "/admin",
  "/results",
  "/auth/",
];

export default function robots(): MetadataRoute.Robots {
  return {
    rules: [
      {
        userAgent: "*",
        allow: ["/", "/en", "/ja", "/de", "/fr", "/zh", "/ko", "/es", "/pt",
                "/pricing", "/features", "/case-studies", "/changelog",
                "/contact", "/demo", "/privacy", "/terms", "/tokushoho", "/dpa",
                "/help", "/support"],
        disallow: APP_PATHS,
      },
    ],
    sitemap: "https://faultray.com/sitemap.xml",
  };
}
